[package]
name = "signer-stronghold"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-consensus = "0.5.4"
alloy-network = "0.5.4"
alloy-primitives = "0.8.9"
alloy-signer = "0.5.4"
async-trait = "0.1.83"
iota_stronghold = "2.1.0"
